dist: xenial
language: python
python:
  - 3.7
  - 3.7-dev

install:
  - pip install -r requirements.txt

script:
  - pytest --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing

after_success:
  - coveralls
